<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Precision Agriculture Platform</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
        }

        nav ul {
            list-style-type: none;
        }

        nav ul li {
            display: inline;
            margin-right: 10px;
        }

        section {
            padding: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        input, textarea {
            margin-bottom: 10px;
            padding: 10px;
        }

        button {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <header>
        <h1>Precision Agriculture Platform</h1>
        <nav>
            <ul>
                <li><a href="#register">Register</a></li>
                <li><a href="#crops">Crops Data</a></li>
                <li><a href="#soil">Submit Soil Sample</a></li>
            </ul>
        </nav>
    </header>

    <section id="register">
        <h2>User Registration</h2>
        <form id="registrationForm">
            <input type="text" id="username" placeholder="Username" required>
            <input type="email" id="email" placeholder="Email" required>
            <input type="password" id="password" placeholder="Password" required>
            <button type="submit">Register</button>
        </form>
    </section>

    <section id="crops">
        <h2>Crops Data</h2>
        <div id="cropData"></div>
    </section>

    <section id="soil">
        <h2>Submit Soil Sample</h2>
        <form id="soilForm">
            <input type="text" id="sampleLocation" placeholder="Sample Location" required>
            <textarea id="soilDetails" placeholder="Soil Details" required></textarea>
            <button type="submit">Submit Sample</button>
        </form>
    </section>

    <script src="script.js"></script>
</body>
</html>
